### ISSUE TITLE
improvement and help

### ISSUE THREAD

**Issue by jonathan-martz** [nrifki/nice-handsome-button#3]
Hello Nada,
first of all thanks for creating your blog post and this nice repo.

I was facing the issue like another guy in the comments of your blog.

I tried to load the component in my router/index.js

Error Message:
Failed to mount component: template or render function not defined.

Then i tried the same wie Vue.use(xyz) in my main.js File.
Everything works.

console.log said something like that.
`
_Ctor: Object [ VueComponent()]
install: function install()
`
Actually it looks okay for me.

After a few hours of trying to fix this problem i found out that the template is working and its also in the component which is returned when importing.

But i know i actually need the component to use it in the vue file components section and the install function is only for global setup.

Short story :grin: 
My final solution was something like that, changing the last few lines of the index.js in the dist folder.
`
var component = normalizeComponent({
    render: __vue_render__,
    staticRenderFns: __vue_staticRenderFns__
  },
  __vue_inject_styles__,
  __vue_script__,
  __vue_scope_id__,
  __vue_is_functional_template__,
  __vue_module_identifier__,
  undefined,
  undefined
);

var setup = {
  install: function install(Vue, options) {
    Vue.component("vue-page-cms", component);
  }
};

module.exports = {
  setup,
  component
};
`

Now i can import it like this.
`
import VuePageCms from '@jonathan-martz/vue-page-cms'
`

After that i can import my component into another vue file like that.
`
export default {
  components: {
    'vue-page-cms': VuePageCms.component,
`

I tried as well the use in the global page ...
`
import VuePageCms from '@jonathan-martz/vue-page-cms'
Vue.use(VuePageCms.setup);
`
... and everything is working here as well.

What do you think is the best solution for this Problem ?
To modify the build, everytime would suck and isnt the solution.

Do you know the rollup-plugin-vue ? 
I thinks thats the point where someone should fix this.

Did you try to run your component in another vue file ?

**Comment by nrifki** [comment]
Hello @jonathan-martz, :)

First of all, I recommend you use this library to build your packages: [vue-sfc-rollup](https://github.com/team-innovation/vue-sfc-rollup).

Also, take a look [at this file](https://github.com/growthbunker/vuedarkmode/blob/master/src/entry.js#L110). Here is how the components can be imported individually (in order to avoid `Vue.use`).
